### ISSUE TITLE
Usage of `COU_DATA` is impossible with snap

### ISSUE THREAD

**Issue by rgildein** [canonical/charmed-openstack-upgrader#152]
Using cou as snap make `COU_DATA` unusable, because the snap has no permission to user home directory.

```bash
$ cou_rg run -v                                                                                                                                                                        
Unexpected error occurred                                                                                                                                                                                          
[Errno 13] Permission denied: '/home/ubuntu/rgildein/log'                                                                                                                                                          
Traceback (most recent call last):                                                                                                                                                                                 
  File "/snap/charmed-openstack-upgrader/x1/lib/python3.10/site-packages/cou/cli.py", line 186, in entrypoint                                                                                                      
    setup_logging(log_level)
  File "/snap/charmed-openstack-upgrader/x1/lib/python3.10/site-packages/cou/logging.py", line 60, in setup_logging
    pathlib.Path(COU_DIR_LOG).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/home/ubuntu/rgildein/log'
```

I think we should support usage of hoe directory and catching exception above with propert message how user can enable it.

**Comment by agileshaw** [comment]
we might need to remove COU_DATA
