### ISSUE TITLE
Unexpected error due empty version

### ISSUE THREAD

**Issue by rgildein** [canonical/charmed-openstack-upgrader#258]
Running COU data-plane planning failed due to invalid version.

```bash
2024-02-22 16:10:54 [cou.cli] [ERROR] Unexpected error occurred.
2024-02-22 16:10:54 [cou.cli] [ERROR] Invalid version: ''
Traceback (most recent call last):
  File "/snap/charmed-openstack-upgrader/x8/lib/python3.10/site-packages/cou/cli.py", line 199, in entrypoint
    loop.run_until_complete(_run_command(args))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/snap/charmed-openstack-upgrader/x8/lib/python3.10/site-packages/cou/cli.py", line 183, in _run_command
    await get_upgrade_plan(args)
  File "/snap/charmed-openstack-upgrader/x8/lib/python3.10/site-packages/cou/cli.py", line 140, in get_upgrade_plan
    analysis_result, upgrade_plan = await analyze_and_plan(args)
  File "/snap/charmed-openstack-upgrader/x8/lib/python3.10/site-packages/cou/cli.py", line 123, in analyze_and_plan
    analysis_result = await Analysis.create(model)
  File "/snap/charmed-openstack-upgrader/x8/lib/python3.10/site-packages/cou/steps/analyze.py", line 108, in create
    return Analysis(model=model, apps_data_plane=data_plane, apps_control_plane=control_plane)
  File "<string>", line 8, in __init__
  File "/snap/charmed-openstack-upgrader/x8/lib/python3.10/site-packages/cou/steps/analyze.py", line 53, in __post_init__
    self.min_os_version_control_plane = self.min_os_release_apps(self.apps_control_plane)
  File "/snap/charmed-openstack-upgrader/x8/lib/python3.10/site-packages/cou/steps/analyze.py", line 167, in min_os_release_apps
    return min((app.current_os_release for app in apps), default=None)
  File "/snap/charmed-openstack-upgrader/x8/lib/python3.10/site-packages/cou/steps/analyze.py", line 167, in <genexpr>
    return min((app.current_os_release for app in apps), default=None)
  File "/snap/charmed-openstack-upgrader/x8/lib/python3.10/site-packages/cou/apps/base.py", line 240, in current_os_release
    os_version = self._get_latest_os_version(unit)
  File "/snap/charmed-openstack-upgrader/x8/lib/python3.10/site-packages/cou/apps/base.py", line 188, in _get_latest_os_version
    compatible_os_versions = OpenStackCodenameLookup.find_compatible_versions(
  File "/snap/charmed-openstack-upgrader/x8/lib/python3.10/site-packages/cou/utils/openstack.py", line 403, in find_compatible_versions
    if version in version_range:
  File "/snap/charmed-openstack-upgrader/x8/lib/python3.10/site-packages/cou/utils/openstack.py", line 324, in __contains__
    service_version = Version(version)
  File "/snap/charmed-openstack-upgrader/x8/lib/python3.10/site-packages/packaging/version.py", line 200, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: ''
```

**Comment by aieri** [comment]
this is quite a corner case, it doesn't fit with the project at the moment
