### ISSUE TITLE
COU: function connect failed

### ISSUE THREAD

**Issue by dparv** [canonical/charmed-openstack-upgrader#428]
This is the error I am getting trying to run cou:

```
$ juju models
Controller: control-node-default

Model       Cloud/Region          Type  Status     Machines  Cores  Units  Access  Last connection
controller  control-node/default  maas  available         1      8  1      admin   just now
openstack*  control-node/default  maas  available        27    104  85     admin   35 seconds ago
```

```
$ cou plan -v
Full execution log: '/home/dparv/.local/share/cou/log/cou-20240531102225.log'  
Connecting to 'admin/openstack' model... \2024-05-31 10:22:25 [INFO] function connect failed [0]
Connecting to 'admin/openstack' model... -2024-05-31 10:22:27 [INFO] function connect failed [1]
Connecting to 'admin/openstack' model... \2024-05-31 10:22:29 [INFO] function connect failed [2]
Connecting to 'admin/openstack' model... |2024-05-31 10:22:31 [INFO] function connect failed [3]
Connecting to 'admin/openstack' model... -2024-05-31 10:22:33 [INFO] function connect failed [4]
Connecting to 'admin/openstack' model... /2024-05-31 10:22:36 [INFO] function connect failed [5]
Connecting to 'admin/openstack' model... ✖
The connection was lost. Check your connection or increase the timeout.
```

**Comment by dparv** [comment]
Ah seems this is the issue:

```
2024-05-31 10:22:33 [cou.utils.juju_utils] [INFO] function connect failed [4]
Traceback (most recent call last):
  File "/snap/charmed-openstack-upgrader/265/lib/python3.10/site-packages/cou/utils/juju_utils.py", line 116, in wrapper
    return await func(*args, **kwargs)
  File "/snap/charmed-openstack-upgrader/265/lib/python3.10/site-packages/cou/utils/juju_utils.py", line 350, in connect
    await self._model.connect(
  File "/snap/charmed-openstack-upgrader/265/lib/python3.10/site-packages/juju/model.py", line 703, in connect
    await self._connector.connect_model(model_name, **kwargs)
  File "/snap/charmed-openstack-upgrader/265/lib/python3.10/site-packages/juju/client/connector.py", line 198, in connect_model
    await self.connect(**kwargs)
  File "/snap/charmed-openstack-upgrader/265/lib/python3.10/site-packages/juju/client/connector.py", line 108, in connect
    raise JujuConnectionError("juju server-version %s not supported" % self._connection.info["server-version"])
juju.errors.JujuConnectionError: juju server-version 3.4.0 not supported
```
