### ISSUE TITLE
[Feature] Check valid nova-cloud-controller configuration scheduler-default-filters

### ISSUE THREAD

**Issue by jneo8** [canonical/charmed-openstack-upgrader#562]
Based on the charm source code [here](https://opendev.org/openstack/charm-nova-cloud-controller/src/commit/b915f8e6f81df6a776fc1ad6725207a199440a3b/hooks/nova_cc_context.py#L421), the charm uses the `scheduler-default-filters` configuration value to set the `enabled_filters` in `/etc/nova/nova.conf`.

However, some of these filters have been deprecated, as shown [here](https://opendev.org/openstack/charm-nova-cloud-controller/src/commit/b915f8e6f81df6a776fc1ad6725207a199440a3b/hooks/nova_cc_context.py#L367-L396). If any deprecated filters are included in the Nova configuration, the `nova-scheduler` service will fail to start.

COU will hit this issue when upgrade from antelope to bobcat. 

I recommend that the COU (Charmed OpenStack Users) check if the configuration is valid or we should contribute to the charm by implementing validation for this configuration.

**Comment by samuelallan72** [comment]
Ah I saw this issue a little too late... I opened a duplicate, and will close it. But I'll save what I wrote here for reference:

---

The filter option `AvailabilityZoneFilter` was [removed](https://opendev.org/openstack/nova/src/branch/master/releasenotes/notes/az-filter-removal-587f7337040b6216.yaml) at some point, in Bobcat [according to charm-nova-cloud-controller](https://opendev.org/openstack/charm-nova-cloud-controller/src/commit/b915f8e6f81df6a776fc1ad6725207a199440a3b/hooks/nova_cc_context.py#L388).

This means that if we have a scenario where `schedule-default-filters` has been set on `nova-cloud-controller` to a value that includes  `AvailabilityZoneFilter`, and we upgrade from antelope to bobcat, then nova-scheduler will crash with the following message in `/var/log/nova/nova-scheduler.log`:

```txt
2024-10-01 10:42:10.920 724488 CRITICAL nova [None req-4a4d2a3f-bd36-434b-a228-11e3e236d034 - - - - - -] Unhandled error: nova.exception.SchedulerHostFilterNotFound: Scheduler Host Filter AvailabilityZoneFilter could not be found.
2024-10-01 10:42:10.920 724488 ERROR nova Traceback (most recent call last):
2024-10-01 10:42:10.920 724488 ERROR nova   File "/usr/bin/nova-scheduler", line 10, in <module>
2024-10-01 10:42:10.920 724488 ERROR nova     sys.exit(main())
2024-10-01 10:42:10.920 724488 ERROR nova   File "/usr/lib/python3/dist-packages/nova/cmd/scheduler.py", line 47, in main
2024-10-01 10:42:10.920 724488 ERROR nova     server = service.Service.create(
2024-10-01 10:42:10.920 724488 ERROR nova   File "/usr/lib/python3/dist-packages/nova/service.py", line 252, in create
2024-10-01 10:42:10.920 724488 ERROR nova     service_obj = cls(host, binary, topic, manager,
2024-10-01 10:42:10.920 724488 ERROR nova   File "/usr/lib/python3/dist-packages/nova/service.py", line 116, in __init__
2024-10-01 10:42:10.920 724488 ERROR nova     self.manager = manager_class(host=self.host, *args, **kwargs)
2024-10-01 10:42:10.920 724488 ERROR nova   File "/usr/lib/python3/dist-packages/nova/scheduler/manager.py", line 68, in __init__
2024-10-01 10:42:10.920 724488 ERROR nova     self.host_manager = host_manager.HostManager()
2024-10-01 10:42:10.920 724488 ERROR nova   File "/usr/lib/python3/dist-packages/nova/scheduler/host_manager.py", line 356, in __init__
2024-10-01 10:42:10.920 724488 ERROR nova     self.enabled_filters = self._choose_host_filters(self._load_filters())
2024-10-01 10:42:10.920 724488 ERROR nova   File "/usr/lib/python3/dist-packages/nova/scheduler/host_manager.py", line 496, in _choose_host_filters
2024-10-01 10:42:10.920 724488 ERROR nova     raise exception.SchedulerHostFilterNotFound(filter_name=msg)
2024-10-01 10:42:10.920 724488 ERROR nova nova.exception.SchedulerHostFilterNotFound: Scheduler Host Filter AvailabilityZoneFilter could not be found.
```

This is not an ideal user experience. COU can improve the user experience for this scenario - some ideas:
- COU could print an error as part of the verification checks when generating a plan (when run on an antelope cloud, if AvailabilityZoneFilter is included in the list)
- COU could automatically adjust the configuration of nova-cloud-controller if it detects this scenario

**Comment by jneo8** [comment]
I will vote for raise an error on verification part and provide step how to change it.
